name: Push/PR pipeline

on:
  push:
    branches:
      - main
      - master
      - renovate/**
  pull_request:

jobs:
  push-pr:
    uses: newrelic/coreint-automation/.github/workflows/reusable_push_pr.yaml@reusable/fix-golangci
    secrets: inherit
    with:
      run_test_build_nix: false
      run_test_build_fake_prerelease: true
      integration: "apache"
