name: Release pipeline
on:
  push:
    branches:
      - testing/action

jobs:
  release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_on_release.yaml@feat/reausable-release-pipeline
    with:
      integration: apache
      tag: "testing-tag"
    secrets: 
      OHAI_AWS_ROLE_ARN_PRODUCTION: "OHAI_AWS_ROLE_ARN_PRODUCTION"
      OHAI_AWS_ACCESS_KEY_ID_PRODUCTION: "OHAI_AWS_ACCESS_KEY_ID_PRODUCTION"
      OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION: "OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION"
      OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION: "OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION"
      OHAI_GPG_PASSPHRASE: "OHAI_GPG_PASSPHRASE"
      OHAI_GPG_PRIVATE_KEY_BASE64: "OHAI_GPG_PRIVATE_KEY_BASE64"
      COREINT_SLACK_TOKEN: "COREINT_SLACK_TOKEN"
      COREINT_SLACK_CHANNEL: "COREINT_SLACK_CHANNEL"
      